add email confirmation for registration
oss2019/crispy-ai pull request #59
Opened 2019-07-23 13:22 UTC by bvishal8510

Solves issue #30 . @NeuralFlux please review.

2019-07-23 13:22 UTC, pep8speaks commented
Hello @bvishal8510! Thanks for opening this PR. 





* In the file [`users/tokens.py`](https://github.com/oss2019/crispy-ai/blob/e55dec5b41884e1aecfbd88d88d9bc281f5d4e38/users/tokens.py):

> [Line 5:73](https://github.com/oss2019/crispy-ai/blob/e55dec5b41884e1aecfbd88d88d9bc281f5d4e38/users/tokens.py#L5): [E262](https://duckduckgo.com/?q=pep8%20E262) inline comment should start with '# '
> [Line 5:101](https://github.com/oss2019/crispy-ai/blob/e55dec5b41884e1aecfbd88d88d9bc281f5d4e38/users/tokens.py#L5): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (119 > 100 characters)
> [Line 6:73](https://github.com/oss2019/crispy-ai/blob/e55dec5b41884e1aecfbd88d88d9bc281f5d4e38/users/tokens.py#L6): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented (comment)
> [Line 9:70](https://github.com/oss2019/crispy-ai/blob/e55dec5b41884e1aecfbd88d88d9bc281f5d4e38/users/tokens.py#L9): [E262](https://duckduckgo.com/?q=pep8%20E262) inline comment should start with '# '
> [Line 9:101](https://github.com/oss2019/crispy-ai/blob/e55dec5b41884e1aecfbd88d88d9bc281f5d4e38/users/tokens.py#L9): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (137 > 100 characters)
> [Line 12:1](https://github.com/oss2019/crispy-ai/blob/e55dec5b41884e1aecfbd88d88d9bc281f5d4e38/users/tokens.py#L12): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> [Line 12:61](https://github.com/oss2019/crispy-ai/blob/e55dec5b41884e1aecfbd88d88d9bc281f5d4e38/users/tokens.py#L12): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`users/urls.py`](https://github.com/oss2019/crispy-ai/blob/e55dec5b41884e1aecfbd88d88d9bc281f5d4e38/users/urls.py):

> [Line 13:43](https://github.com/oss2019/crispy-ai/blob/e55dec5b41884e1aecfbd88d88d9bc281f5d4e38/users/urls.py#L13): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\-'
> [Line 14:9](https://github.com/oss2019/crispy-ai/blob/e55dec5b41884e1aecfbd88d88d9bc281f5d4e38/users/urls.py#L14): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 15:9](https://github.com/oss2019/crispy-ai/blob/e55dec5b41884e1aecfbd88d88d9bc281f5d4e38/users/urls.py#L15): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent



Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2019-07-25 16:41 UTC, svp19 requested changes
@bvishal8510
- Do change the subject from `Activate your Phoics account` to `Activate your activate Crispy AI account`.
- Also, I got a WARNING while running `python manage.py migrate`

<pre>WARNINGS:                                                                                                                                                                    
<font color="#C4A000"><b>?: (2_0.W001) Your URL pattern &apos;^activate/(?P&lt;uidb64&gt;[0-9A-Za-z_\-]+)/(?P&lt;token&gt;[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$&apos; [name=&apos;activate&apos;] has a route that contains &apos;(?P&lt;&apos;, b</b></font>
<font color="#C4A000"><b>egins with a &apos;^&apos;, or ends with a &apos;$&apos;. This was likely an oversight when migrating to django.urls.path().</b></font></pre>

**FIX**
This is because `path()` in Django 2.0 doesn't use regular expressions. Use `re_path()` instead.

See more https://stackoverflow.com/questions/47661536/django-2-0-path-error-2-0-w001-has-a-route-that-contains-p-begins-wit

~ The rest works as expected :)

2019-07-27 06:04 UTC, bvishal8510 commented
@svp19 please review the changes.

2019-07-27 13:02 UTC, svp19 approved these changes

2019-07-27 13:03 UTC, merged